export const BACKGROUNDS_LOADING = 'app/Statistic/BACKGROUNDS_LOADING';
export const STATISTIC_LOADING_ERROR = 'app/Statistic/STATISTIC_LOADING_ERROR';
export const STATISTIC_SUCCESSFULLY_LOADED = 'app/Statistic/STATISTIC_SUCCESSFULLY_LOADED';
